// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    paths: {
      "backbone": "components/backbone/backbone-min",
      "underscore": "components/underscore/underscore-min",
      "jquery": "components/jquery/jquery.min"
    },
    shim: {
      "backbone": {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      },
      "underscore": {
        exports: "_"
      },
      "jquery": {
        exports: "$"
      }
    }
  });

  require(["backbone", "models/slide", "views/entireView"], function(Backbone, Slide, EntireView) {
    return $(function() {
      var PAGES, PJAX, REPEAT, entireView, mediaQueryList, slide;

      PAGES = 'section';
      REPEAT = true;
      PJAX = false;
      slide = new Slide;
      entireView = new EntireView({
        model: slide,
        pages: PAGES,
        repeat: REPEAT
      });
      entireView.initCSS();
      entireView.listenTo(slide, 'change:page', entireView.showPage);
      entireView.listenTo(slide, 'change:altitude', entireView.zoom);
      $(PAGES).click(function(e) {
        var clickedPage;

        e.preventDefault();
        clickedPage = $(PAGES).index($(this));
        slide.set({
          'page': clickedPage
        });
        return entireView.zoomIn();
      });
      mediaQueryList = window.matchMedia('print');
      return mediaQueryList.addListener(function(mql) {
        if (mql.matches) {
          return $(PAGES).parent().css({
            'display': 'inline'
          });
        } else {
          return $(PAGES).parent().css({
            'display': 'flex',
            'display': '-webkit-flex'
          });
        }
      });
    });
  });

}).call(this);
