// Generated by CoffeeScript 1.6.2
(function() {
  var EntireView, PAGES, PJAX, REPEAT, Slide, firstPage, lastPage;

  PAGES = 'section';

  PJAX = false;

  REPEAT = true;

  Slide = Backbone.Model.extend({
    defaults: {
      page: 0
    }
  });

  EntireView = Backbone.View.extend({
    el: 'html',
    events: {
      'keydown': 'onKeyDown'
    },
    initCSS: function() {
      this.$el.css('overflow', 'hidden');
      $(PAGES).parent().css({
        'display': 'flex',
        /* 
        jquery1.9.1 does not automatically add vendor prefix with 'flex'.
        and also, only Chrome supports 'flex' for now.
        */

        'display': '-webkit-flex',
        'flex-wrap': 'nowrap',
        'align-items': 'center',
        'min-width': "" + ($(PAGES).size() * 100) + "%"
      });
      return $(PAGES).css({
        'display': 'flex',
        'display': '-webkit-flex',
        'justify-content': 'space-around',
        'align-items': 'center',
        'flex-direction': 'column',
        'width': '100%',
        'min-height': $(window).height(),
        'transition': function(index, value) {
          return 'all 1s ease';
        }
      });
    },
    zoomIn: function() {
      return this.$el.css({
        'transform': 'scale3d(1.0, 1.0, 1.0)',
        'transition': 'transform 1s ease',
        'transition': '-webkit-transform 1s ease'
      });
    },
    zoomOut: function() {
      return this.$el.css({
        'transform': 'scale3d(0.5, 0.5, 0.5)',
        'transition': 'transform 1s ease',
        'transition': '-webkit-transform 1s ease'
      });
    },
    showPage: function() {
      return $(PAGES).css('transform', "translateX(-" + (this.model.get('page') * 100) + "%)");
    },
    onKeyDown: function(e) {
      var destination;

      switch (e.which) {
        case 38:
          e.preventDefault();
          return this.zoomOut();
        case 40:
          e.preventDefault();
          return this.zoomIn();
        case 33:
        case 37:
        case 75:
          e.preventDefault();
          destination = this.model.get('page') - 1;
          if (destination < firstPage()) {
            destination = REPEAT ? lastPage() : firstPage();
          }
          return this.model.set({
            'page': destination
          });
        case 13:
        case 32:
        case 34:
        case 39:
        case 74:
          e.preventDefault();
          destination = this.model.get('page') + 1;
          if (destination > lastPage()) {
            destination = REPEAT ? firstPage() : lastPage();
          }
          return this.model.set({
            'page': destination
          });
        case 36:
        case 48:
          e.preventDefault();
          return this.model.set({
            'page': firstPage()
          });
        case 35:
        case 52:
          e.preventDefault();
          return this.model.set({
            'page': lastPage()
          });
      }
    }
  });

  firstPage = function() {
    return 0;
  };

  lastPage = function() {
    return $(PAGES).size() - 1;
  };

  $(function() {
    var entireView, slide;

    slide = new Slide;
    entireView = new EntireView({
      model: slide
    });
    entireView.initCSS();
    entireView.listenTo(slide, 'change:page', entireView.showPage);
    return $(PAGES).click(function(e) {
      var clickedPage;

      e.preventDefault();
      clickedPage = $(PAGES).index($(this));
      slide.set({
        'page': clickedPage
      });
      return entireView.zoomIn();
    });
  });

}).call(this);
