// Generated by CoffeeScript 1.6.2
(function() {
  define(["backbone"], function(Backbone) {
    var Slide;

    return Slide = Backbone.Model.extend({
      defaults: {
        page: 0,
        altitude: 0
      }
    });
  });

}).call(this);
